[package]
name = "technology9"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bon = "3.9.2"
bytemuck = "1.25.0"
dashmap = "6.2.1"
env_logger = "0.11.10"
glam = { version = "0.33.1", features = ["bytemuck"] }
image = "0.25.10"
kira = "0.12.1"
log = "0.4.32"
noise = "0.9.0"
pollster = "0.4.0"
rand = "0.10.1"
rustc-hash = "2.1.2"
wgpu = "29.0.3"
winit = "0.30.13"

[profile.dev]
lto = false
opt-level = 1
codegen-units = 256
incremental = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
panic = "abort"
opt-level = 3
codegen-units = 4
overflow-checks = false
strip = true

[profile.release.package."*"]
opt-level = 3

[profile.profiling]
inherits = "release"
lto = false
debug = true

[profile.profiling.package."*"]
opt-level = 3

[[bin]]
name = "game"
path = "./src/main.rs"

